<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TxtPhoneNumber</name>
   <tag></tag>
   <elementGuidId>ddfd2bf6-ec71-47f6-a499-cd8fae4f17c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/section/div/div[2]/div[2]/div/section[2]/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d653342-ed05-434b-9053-502d5fda23cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DataDisplay-value</value>
      <webElementGuid>a0eb32be-c965-4b1d-83fe-30987bc66e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>e9afe55b-3c9a-452f-a63b-899b126574c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Main theme-primary&quot;]/div[1]/section[@class=&quot;wrapper has--navigation&quot;]/div[1]/div[@class=&quot;u-Flex&quot;]/div[@class=&quot;DeliveryStatusDetail u-ai-flexStart&quot;]/div[@class=&quot;Card u-MarginLeft u-MarginBottom&quot;]/section[@class=&quot;Card-body&quot;]/div[@class=&quot;u-Flex&quot;]/div[1]/div[@class=&quot;DataDisplay u-MarginBottom&quot;]/div[@class=&quot;DataDisplay-value&quot;]</value>
      <webElementGuid>371258da-c2ed-4d51-a73e-1b19c661d25f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/div[2]/div[2]/div/section[2]/div/div/div[2]/div</value>
      <webElementGuid>5945780d-ec4e-43ba-b248-3af14a7e44b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Handphone'])[1]/following::div[1]</value>
      <webElementGuid>9cc2455e-f5d5-40c9-9064-88d93caa9ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::div[2]</value>
      <webElementGuid>221e68d9-4466-427d-96a2-ce55e27d4cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Kiriman'])[1]/preceding::div[1]</value>
      <webElementGuid>46b2d325-60f0-440c-96a4-41d8999620ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::div[45]</value>
      <webElementGuid>84e497d6-5642-4ab2-ac75-9db33565b867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div[2]/div</value>
      <webElementGuid>2d246fdd-7134-4c74-8647-559a4f11c0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '-' or . = '-')]</value>
      <webElementGuid>3130fa95-683d-4ede-bd81-67501d81b698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
