<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnEndVideoCall</name>
   <tag></tag>
   <elementGuidId>504d8d98-d06a-45a5-9098-725e93486ca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BtnEndCall</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnEndCall']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a491d47d-596b-4722-9d21-96a59c94acde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button EndCallButton</value>
      <webElementGuid>d6e16a04-dc0b-49a0-884b-3aec360e9fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnEndCall</value>
      <webElementGuid>984f8af9-ec6a-4816-a558-7b43705065f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0cf37d13-f026-4c92-ab54-337399d9da45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selesai Video Call </value>
      <webElementGuid>7016d475-f84c-482e-8c7a-73b16c47002a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnEndCall&quot;)</value>
      <webElementGuid>f82a077b-6ac1-4674-9df3-d123b8c69809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnEndCall']</value>
      <webElementGuid>2748c039-e56a-4a02-9e38-7d644e717464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/section/form/div[4]/div/section[2]/div/div[2]/button</value>
      <webElementGuid>e69b5e9f-54a7-4fd8-ae41-a8d333ff904e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ambil Foto'])[1]/following::button[1]</value>
      <webElementGuid>99abef67-8af3-41a2-8b56-2746be223ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koneksi internet sudah terhubung. Video call dapat dilanjutkan kembali'])[1]/following::button[1]</value>
      <webElementGuid>fd6d0c69-aa77-4dc9-9bb8-c861ebab8127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hal-hal yang perlu dikonfirmasi'])[1]/preceding::button[1]</value>
      <webElementGuid>6e8c22c6-99eb-4af9-b8bb-ec47657a33d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menanyakan Nama Sesuai KTP'])[1]/preceding::button[1]</value>
      <webElementGuid>90ceca69-3d3a-4b5a-b51f-871b23b5e493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selesai Video Call']/parent::*</value>
      <webElementGuid>23f3c5aa-d6db-4487-abe3-09052835a189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9cca1d74-5de4-48ce-8946-49f46e5e6782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnEndCall' and @type = 'button' and (text() = 'Selesai Video Call ' or . = 'Selesai Video Call ')]</value>
      <webElementGuid>1dd546d0-fcce-4b78-9241-c483ca5c5b03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
