<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chkIdNo</name>
   <tag></tag>
   <elementGuidId>b614ceae-8fd7-46b2-b2b8-8cd980179cd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ChkKtpNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ChkKtpNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec9196f5-b1dc-428c-8a6b-4906fca9e862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChkKtpNumber</value>
      <webElementGuid>21cb92bc-c776-4eda-af13-a40f4f7b65e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c99c06cb-f9d0-4cbb-9b75-0c8f213f5eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ktpNumber</value>
      <webElementGuid>14cf171c-d0e3-4dfc-b9b2-6f920c9f598d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ChkKtpNumber&quot;)</value>
      <webElementGuid>abe7c6b8-b495-44c0-b0c1-20ff5d42de54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ChkKtpNumber']</value>
      <webElementGuid>dca27c57-60d7-4aa4-917d-9b4dbc12c486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/section/form/div[4]/div[2]/div[3]/div/input</value>
      <webElementGuid>88ab8d12-f65d-42a7-a72b-061c9d04fc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8a9c1f4d-3381-4a5f-a222-9ccad2b8ffd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ChkKtpNumber' and @type = 'checkbox' and @name = 'ktpNumber']</value>
      <webElementGuid>bdb87518-1428-46eb-ad90-72b6d8653efc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
