<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chkPhotoIsNotSame</name>
   <tag></tag>
   <elementGuidId>b7de502f-66bb-4d9a-a26c-2e2fd19c727b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ChkPhotoIsNotSame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ChkPhotoIsNotSame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>977dd57a-92f8-481c-9335-45da658e793e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChkPhotoIsNotSame</value>
      <webElementGuid>89ade710-1c0c-4d59-add5-c7c631ee2c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>62d0ffc4-e45a-4d62-9478-cac1d3f7f690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>photoIsNotSame</value>
      <webElementGuid>f074b945-5e57-40ab-9ed7-55d6a1f6d89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ChkPhotoIsNotSame&quot;)</value>
      <webElementGuid>d73d180c-7fee-4e7d-ba99-0d160ecec2b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ChkPhotoIsNotSame']</value>
      <webElementGuid>bbcec0c0-e29d-47b3-99b1-9b819d0e0880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outer-root']/div/div/section/form/div/div[6]/div/input</value>
      <webElementGuid>aaf0273c-399d-4ee2-9be7-5ac19705e547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[6]/div/input</value>
      <webElementGuid>a12445ac-d643-4376-959c-45e50843e101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ChkPhotoIsNotSame' and @type = 'checkbox' and @name = 'photoIsNotSame']</value>
      <webElementGuid>6918df32-cd92-4091-8fcd-0da2950845e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
