<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TxtFirstRowDataColumn</name>
   <tag></tag>
   <elementGuidId>df5d54ec-afee-4ced-a82e-b20532d53047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Courier Type'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnReqId1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b4706df0-f684-4107-9df1-2f6b36319b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button Button--secondary Button--small</value>
      <webElementGuid>19c8e2ba-6011-4d0a-a862-f78c47a5fc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnReqId1</value>
      <webElementGuid>8242177e-db18-4c70-a882-994a04d28fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/card-management/delivery-status/10001294</value>
      <webElementGuid>7103ee97-f9f8-441e-b578-1e86b874b650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10001294 </value>
      <webElementGuid>73df734b-aa5b-450c-9664-169a201c9047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnReqId1&quot;)</value>
      <webElementGuid>a7199067-505b-411a-b8d8-f59a75226c4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='BtnReqId1']</value>
      <webElementGuid>5df0bcc5-c648-46f5-a960-8345bb0f9167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/section/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>f19cc343-9135-4c1b-bbbb-677ec8ecf20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'10001294')]</value>
      <webElementGuid>9e910201-bc1c-477b-8c3c-053c3465630f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Status'])[4]/following::a[1]</value>
      <webElementGuid>15f1f2aa-2196-4ceb-bf35-2565232ff6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Courier Type'])[1]/following::a[1]</value>
      <webElementGuid>3d66e728-a10f-414a-9f20-e462c341dde1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MOHAMMAD FATHI WIBOWO'])[1]/preceding::a[1]</value>
      <webElementGuid>2e7e8dcb-7788-4f4c-8bec-90e1d9088bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permintaan Kartu Baru'])[2]/preceding::a[1]</value>
      <webElementGuid>9c6d1086-5800-4473-a808-8178c977f08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10001294']/parent::*</value>
      <webElementGuid>5643c48f-4404-489d-9939-9780babf8ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/card-management/delivery-status/10001294')]</value>
      <webElementGuid>62cc9a63-429d-4b14-9975-41a7fedf6b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>66b3168b-1726-4772-9a34-de1a5cc3d5b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'BtnReqId1' and @href = '/card-management/delivery-status/10001294' and (text() = '10001294 ' or . = '10001294 ')]</value>
      <webElementGuid>4cc027f9-2a9f-4058-9bc9-a9d394b659c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
