<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chkKtpImage</name>
   <tag></tag>
   <elementGuidId>0da3dd26-de9e-4ca6-a409-291484daac2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ChkKtpImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ChkKtpImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63b85e2b-2d0a-444f-a43a-7d600be823d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChkKtpImage</value>
      <webElementGuid>65ab8c23-cafa-42c6-a079-b465d7aee870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8bf022f8-82a5-410d-bb33-00d642c36634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ktpImage</value>
      <webElementGuid>a16f9537-97c8-466e-9e8a-fb008a95571c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ChkKtpImage&quot;)</value>
      <webElementGuid>3782ee40-fe08-4373-926b-b3bd931af551</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ChkKtpImage']</value>
      <webElementGuid>47b1f9b9-6dd1-4ab5-9b3e-446485e9fd37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/section/form/div[4]/div[2]/div[7]/div/input</value>
      <webElementGuid>d3a17a77-ba2c-4c2c-bc6d-2a3c47efd35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>6aa60002-b7e9-4bef-83d9-5a2ad9719fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ChkKtpImage' and @type = 'checkbox' and @name = 'ktpImage']</value>
      <webElementGuid>b2de7c9a-a18a-4a33-ab6e-00c7ee181e30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
