<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DashboardOopsText</name>
   <tag></tag>
   <elementGuidId>805c8607-ddf5-408b-9c15-aef6d477c393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.u-MarginBottom-xxsmall</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>3620f907-0938-4dd1-98ef-2bd6201283c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-MarginBottom-xxsmall</value>
      <webElementGuid>020712b0-b3d5-44af-80b7-cda31c95bf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oops!</value>
      <webElementGuid>53a17726-10a0-4ec3-a32c-4ee314617b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Main theme-primary&quot;]/div[1]/div[@class=&quot;wrapper center&quot;]/div[@class=&quot;u-Align-center&quot;]/h3[@class=&quot;u-MarginBottom-xxsmall&quot;]</value>
      <webElementGuid>6b989112-a248-4f77-8388-d62caa3b4b94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/h3</value>
      <webElementGuid>5fa2daaf-3d4a-495c-ab15-454b6bbda083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::h3[1]</value>
      <webElementGuid>bbe2d3e1-aa68-435d-a834-24cf5ba8a25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::h3[1]</value>
      <webElementGuid>47566ac1-dc17-4110-a4cf-4db3a1edc0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::h3[1]</value>
      <webElementGuid>55d490fb-9c5b-40d9-8ee1-ede34ca35697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::h3[1]</value>
      <webElementGuid>43cc0c86-ac22-4ffc-b8a8-a32b2f07a130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Oops!']/parent::*</value>
      <webElementGuid>2e4595fe-13aa-45ac-8d31-9234b15deff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>872f6c65-2f99-4b60-bd58-53d994b3020e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Oops!' or . = 'Oops!')]</value>
      <webElementGuid>145d2f84-3413-48e6-9cee-d7a04ad1e99b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
