<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>https://bankamar.testrail.io/index.php?/tests/view/1350214</description>
   <name>Suite_CSRManagement_Bucket_List_T1350214</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>27d03e75-8de9-4695-a5e1-f52995b1ee47</testSuiteGuid>
   <testCaseLink>
      <guid>fa1407ca-44b2-4c7f-bf32-6c7badcd4dc4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/URL/URL_Staging_CRM</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56816ae0-de95-4d26-b12c-87f914ebfa19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91dc2b1a-941d-4528-9e9a-686b8ccd402b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4348dd33-86dc-4f59-9c4d-67bbb0fc4677</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6032f729-d80e-4525-97b5-13e6c0d34ad2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>585d95a3-94f9-4949-a96d-4a9c05ce0a8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b295f90a-5f17-4122-9a18-654f3f60c646</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9cdaae5-c4e9-4c21-8d8f-bc63c0eada6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c1921ec-09d7-4b13-955a-6d104803872f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Website/CRM/CRM_Login/TC_Login_Security_Question_CSRManagement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff753ff5-d6bb-4c3c-86ca-a4ffee4e3e2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b02fef10-38df-4afb-a201-290e32809ebf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fcfdc28-5382-4663-886b-71ec0cc65ee7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c9dcfdb-af87-465e-992c-63d9c635e890</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bdb6a02d-21db-4732-8e7d-63a1939b518b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Website/CRM/CRM_CSRManagement/CSRManagement_BucketListPage/TC_CantPassSecQuestBirthday</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5087d6e1-d725-4580-b64e-7ebdb82c50e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8affa15-89c3-4c48-b6ca-cea005cb7941</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>691d5ffe-ed7a-446b-aa6c-3adc6da3899e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1aa3f0c-0862-47e0-814b-8bc0d7cc8e1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a7142ee-5f3b-427b-90b8-91cc759aa133</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4eb0416-b6c1-4c3e-9860-00382faa4ed6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e64eaf8-1f8a-4e9a-8547-c687438af9a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a98467c-9c41-4c29-b1d2-865c0541b4f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>833f0380-99c5-471f-b185-175d5a9492b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06b47e02-45d3-4e05-b3b5-47cbd206c244</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60881368-68cc-4d4e-aa90-2ba9a704a11e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b58199e-4ab3-425b-9020-f15209370896</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9447152-ec62-4355-8b44-8e791a807d68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc9fca09-e2ca-4b01-bade-7c986d0d57af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71f8178b-1d81-40ba-ac1c-8d3dc5e003eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afa1efb9-9435-445a-881f-7ee3c41040a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b3071f81-99fe-45b7-9cba-a5378d436d74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Website/CRM/CRM_Logout/TC_Logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>427aee94-b04c-4d8c-b3c4-c64a99bd2699</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>469c9a65-336a-46ce-92ec-13754252de72</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
