<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DeliveryStatusTxtHeaderBucketlist</name>
   <tag></tag>
   <elementGuidId>ea1755b8-a0b0-41e4-a1c8-10cbdc027de7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/section/div/ul/li[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8aec9115-061b-4961-8c0d-681d58ff3d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delivery Status</value>
      <webElementGuid>ef7aca01-b8fc-45fc-af80-e67505bf1988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Main theme-primary&quot;]/div[1]/section[@class=&quot;wrapper has--navigation&quot;]/div[1]/ul[@class=&quot;Breadcrumb u-MarginBottom-xlarge&quot;]/li[@class=&quot;Breadcrumb-item&quot;]/span[1]</value>
      <webElementGuid>77f35eb5-2da5-4ac4-bc48-6ea7ebe66f88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/ul/li[3]/span</value>
      <webElementGuid>61c682bc-ed2e-43c0-979c-be5f938ea2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/following::span[1]</value>
      <webElementGuid>3a57c949-7c6d-4591-ad2e-3728de13b56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Management'])[2]/following::span[2]</value>
      <webElementGuid>9a86f176-92e4-48ef-9872-23bbd7ce1d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Request ID atau Ref ID nasabah'])[1]/preceding::span[1]</value>
      <webElementGuid>4f4bfcfb-455a-4c1f-a44a-2ea55672b632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter Tanggal'])[1]/preceding::span[1]</value>
      <webElementGuid>c188164c-35a2-4dc1-a6de-f73523ae3299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span</value>
      <webElementGuid>0661ba1c-b6e4-4a8d-9d72-6f6cf3cf82f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Delivery Status' or . = 'Delivery Status')]</value>
      <webElementGuid>f728c722-e912-4ed9-bfac-209b6739539a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
