<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AlertReferalNotRegist</name>
   <tag></tag>
   <elementGuidId>319af2c5-1d29-4ab1-bd72-553c351abca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='referralby']/div/div/div[2]/section/form/section/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.u-Flex.u-ai-center.u-fs-large</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bfbec87c-0c20-42b4-96dd-5360f2ad842f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-Flex u-ai-center u-fs-large</value>
      <webElementGuid>a59bb0cf-378f-47ac-aac5-2052b61a85e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kode Referal tidak terdaftar</value>
      <webElementGuid>31bc8a6b-bd44-4e81-b972-cf3396bed5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;referralby&quot;)/div[@class=&quot;Accordion&quot;]/div[@class=&quot;Card&quot;]/div[@class=&quot;Accordion-body&quot;]/section[@class=&quot;Card-body&quot;]/form[@class=&quot;Form&quot;]/section[@class=&quot;SectionButtons u-mg-bottom u-mg-top&quot;]/div[@class=&quot;Alert Alert--danger u-mg-bottom u-pd-base&quot;]/div[@class=&quot;Grids&quot;]/div[@class=&quot;Grid Grid-xs-8&quot;]/div[@class=&quot;u-Flex u-ai-center u-fs-large&quot;]</value>
      <webElementGuid>8c802fce-a415-4b3f-a295-70c64f2e98a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='referralby']/div/div/div[2]/section/form/section/div/div/div/div</value>
      <webElementGuid>2e42d8e5-f03d-43e3-918e-de2fef9043b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Referal'])[2]/following::div[5]</value>
      <webElementGuid>1e306a57-8721-4ac5-a874-96b73a718de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Referal'])[1]/following::div[10]</value>
      <webElementGuid>59eebb7b-a00b-4344-a1b4-51086026ec97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[2]</value>
      <webElementGuid>9ce8d101-b12f-4d86-af9d-ee9c787d8e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::div[2]</value>
      <webElementGuid>8bb747fc-6ea9-4c9a-9857-a3b851477b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kode Referal tidak terdaftar']/parent::*</value>
      <webElementGuid>c72cd08b-6bfa-42d3-9742-7c5b11bcd024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div</value>
      <webElementGuid>80eac836-ef53-4881-a27a-ba71b127e1fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kode Referal tidak terdaftar' or . = 'Kode Referal tidak terdaftar')]</value>
      <webElementGuid>7d480599-d76e-4e70-a652-05ec466a6152</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
