<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AlertPurporseOpeningAccount</name>
   <tag></tag>
   <elementGuidId>9970126a-6860-4d84-9b8d-6f3b1dfdb325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.u-fs-small.u-clr-danger.u-mg-top-xxsmall</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[3]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4eb39cbe-a52f-49b7-b73e-b1791e66674b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-fs-small u-clr-danger u-mg-top-xxsmall</value>
      <webElementGuid>7b5440f8-8f9e-40f6-ae37-b525837daa35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tujuan pembuatan rekening wajib dipilih</value>
      <webElementGuid>28e20c35-bf92-49bd-a90c-d106bdee2ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PersonalDataForm&quot;)/form[@class=&quot;Form&quot;]/div[@class=&quot;Grids&quot;]/div[@class=&quot;Grid&quot;]/div[@class=&quot;Form-field Form-field--danger&quot;]/div[@class=&quot;u-fs-small u-clr-danger u-mg-top-xxsmall&quot;]</value>
      <webElementGuid>3e4935f9-7dea-47f6-92a0-570e10ab9c10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PersonalDataForm']/form/div/div[2]/div[3]/div[2]</value>
      <webElementGuid>df08e3e9-4d52-4f66-affe-5e3e64122cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tujuan pembuatan rekening'])[1]/following::div[3]</value>
      <webElementGuid>bf8e3699-40f3-43f6-841f-74fd11d02c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Kerabat'])[1]/following::div[5]</value>
      <webElementGuid>1982207e-9b35-44e1-a80e-2ed1afc9e082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[1]</value>
      <webElementGuid>f008d8c7-d301-44af-8bca-3b4c63e6e256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[5]/preceding::div[1]</value>
      <webElementGuid>48ad8c75-3767-4dbf-9789-9b3ba140abdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tujuan pembuatan rekening wajib dipilih']/parent::*</value>
      <webElementGuid>efcaf096-7153-42f7-9bee-77c3debf78c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]</value>
      <webElementGuid>7fc863df-0afc-459d-b615-a8ba9740f15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tujuan pembuatan rekening wajib dipilih' or . = 'Tujuan pembuatan rekening wajib dipilih')]</value>
      <webElementGuid>1827b5e0-1bbe-4679-9467-765bf6d4e6ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
