<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TxtHeaderBlockCard</name>
   <tag></tag>
   <elementGuidId>b5126885-3095-4697-803e-21aa2cf9be9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outer-root']/div/div/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h5.u-FontWeight-bold.u-MarginBottom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>aa6e139b-be68-4e8d-b1a0-c29c5910d486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-FontWeight-bold u-MarginBottom</value>
      <webElementGuid>066178c3-6168-4d46-9c91-097212ab4708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Block Kartu ATM</value>
      <webElementGuid>3ec8e753-156b-4c5a-b5ee-f465f285fc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outer-root&quot;)/div[@class=&quot;Modal is-opened&quot;]/div[@class=&quot;Modal-dialog BlockCardModal&quot;]/h5[@class=&quot;u-FontWeight-bold u-MarginBottom&quot;]</value>
      <webElementGuid>95e0d78f-8d9e-4f33-995a-316441cb0755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outer-root']/div/div/h5</value>
      <webElementGuid>cd084fcc-cb0c-4345-8b2b-24bcb557cd8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Log'])[2]/following::h5[1]</value>
      <webElementGuid>298c7589-c368-4a11-8f9b-b5feaf53a4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIN Transaksi'])[2]/following::h5[1]</value>
      <webElementGuid>d01d592a-3bf2-4230-8dde-b506accccbe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hal-hal yang perlu dikonfirmasi dalam block kartu ATM'])[1]/preceding::h5[1]</value>
      <webElementGuid>7c5ada1e-89dc-4c6a-8bad-f94c4b0f88e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menanyakan nama ibu kandung'])[1]/preceding::h5[2]</value>
      <webElementGuid>b4b9bc24-c72d-43ba-835c-45f50af99e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Block Kartu ATM']/parent::*</value>
      <webElementGuid>9c201ba2-6112-4d53-8dbb-aa11ac46160b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>c76f0f5f-e2e5-4fc3-b7d8-a2d4283f4e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Block Kartu ATM' or . = 'Block Kartu ATM')]</value>
      <webElementGuid>3516fabb-cb68-4dff-a036-d0ea3d451286</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
