<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TxtHeaderUnblockCard</name>
   <tag></tag>
   <elementGuidId>cc384430-04fd-43f0-a3d2-2a9c51c1443c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5.u-FontWeight-bold.u-MarginBottom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outer-root']/div/div/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>2c76b40b-7e11-43d6-8ebd-e9c8475d46a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-FontWeight-bold u-MarginBottom</value>
      <webElementGuid>cd7978a4-05a5-4a80-ab7c-bafec8665da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unblock Kartu ATM</value>
      <webElementGuid>8807f6c3-d30d-47d9-bc40-591709db2796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outer-root&quot;)/div[@class=&quot;Modal is-opened&quot;]/div[@class=&quot;Modal-dialog UnblockCardModal&quot;]/h5[@class=&quot;u-FontWeight-bold u-MarginBottom&quot;]</value>
      <webElementGuid>b4b03ac8-fc45-4883-a860-d7c423a63aaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outer-root']/div/div/h5</value>
      <webElementGuid>98bb771f-31ba-48cf-9a3d-1900092373fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Log'])[2]/following::h5[1]</value>
      <webElementGuid>c4b8ce7d-e61c-4a47-9ba2-68841a67ebff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIN Transaksi'])[2]/following::h5[1]</value>
      <webElementGuid>38b9c2e9-d417-417b-893a-fd48a7689f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hal-hal yang perlu dikonfirmasi dalam unblock kartu ATM'])[1]/preceding::h5[1]</value>
      <webElementGuid>62ee38c7-2f33-4cb3-8f81-dc282f7b43cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menanyakan nama ibu kandung'])[1]/preceding::h5[2]</value>
      <webElementGuid>7c9379ac-3b89-4a12-9bb5-b55f1eb18dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unblock Kartu ATM']/parent::*</value>
      <webElementGuid>77850916-372f-475b-ab78-a3da0cd26333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>1bcb153a-f458-4237-a414-d8e5d6304a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Unblock Kartu ATM' or . = 'Unblock Kartu ATM')]</value>
      <webElementGuid>d4983c82-68b4-4b37-bead-d010f8d38de9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
