<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TxtRequestNewCard</name>
   <tag></tag>
   <elementGuidId>0c674328-b972-4c98-8056-98775752ae20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccountInfoForm']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c1de9265-fc7b-42a6-858b-f6d484ab02d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Permintaan Kartu Baru</value>
      <webElementGuid>a3c98f79-5cd3-41e4-bfbc-9173ce5167a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountInfoForm&quot;)/div[@class=&quot;u-Flex u-MarginBottom&quot;]/div[2]</value>
      <webElementGuid>5384973b-dfbf-4516-bbff-bb54dc1b2779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccountInfoForm']/div/div[2]</value>
      <webElementGuid>f7ab2ba9-bb14-470f-8f29-fc64c59b9b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Aktivasi'])[1]/following::div[1]</value>
      <webElementGuid>c8d926e0-1fb7-45d7-8e60-9f9eb28f5524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Kartu ATM'])[1]/following::div[6]</value>
      <webElementGuid>9de4fff9-6171-48f6-b86a-8deb972793f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.Rekening'])[1]/preceding::div[1]</value>
      <webElementGuid>acb62d57-172a-4a5a-bd4d-1322d4ea7052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[11]/div/div/div[2]/section/div/div/div[2]</value>
      <webElementGuid>416da7be-28ae-4b86-ac89-714865d91b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Permintaan Kartu Baru' or . = 'Permintaan Kartu Baru')]</value>
      <webElementGuid>2e81a7ee-9a38-4349-8e60-f7c26465331d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
