<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BtnVerify</name>
   <tag></tag>
   <elementGuidId>fc9e4e10-28c5-417b-bdab-87bfc379bab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnVerify']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnVerify</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54b3a6d7-b548-470e-839a-e20d3f67b195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button Button--secondary Button--fullWidth</value>
      <webElementGuid>ed0bc064-f34f-43b7-b822-346c46824bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1e967f56-fbbc-47e4-8fa3-df611db090e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnVerify</value>
      <webElementGuid>8044670f-e5ec-4257-ba7a-cfea07c52380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verifikasi Kode</value>
      <webElementGuid>5e8833e0-93fd-45b3-b3d3-0f09f22dcd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnVerify&quot;)</value>
      <webElementGuid>f2eb7cfe-1d73-40d0-ad4d-1921eb6bbd7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnVerify']</value>
      <webElementGuid>30125a9f-4379-42e4-b853-a9f5490cff42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div/div/form/div/button</value>
      <webElementGuid>4dd44107-78ed-494e-845f-753737457a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ganti nomor handphone'])[1]/following::button[1]</value>
      <webElementGuid>e43b9770-231f-403d-9d06-95e1a2ddb0e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unduh Senyumku'])[2]/following::button[1]</value>
      <webElementGuid>b87bd810-8dcc-466b-99ae-35f599151117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senyumku adalah produk PT Bank Amar Indonesia yang terdaftar dan diawasi oleh'])[1]/preceding::button[1]</value>
      <webElementGuid>254d9d70-9a6a-4478-9dd0-b491a150ce98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Senyumku'])[1]/preceding::button[1]</value>
      <webElementGuid>b5b61054-ba6f-4c00-9a79-0a57e4cd158a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verifikasi Kode']/parent::*</value>
      <webElementGuid>d891a8af-5cf3-4818-ba56-e5ee2936bb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>98d50fe6-93ac-475b-b2d1-59b98a6734bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'BtnVerify' and (text() = 'Verifikasi Kode' or . = 'Verifikasi Kode')]</value>
      <webElementGuid>f2afee28-004e-4b17-9342-1bcb29d64ef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
