<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DrpDistrictReactivation</name>
   <tag></tag>
   <elementGuidId>be1dc6ee-426d-40c7-bc51-b3e7ab0ae6a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DrpDistrict']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DrpDistrict</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>105a3b1e-a891-400b-807d-d422b3489e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>1517bc37-ea27-4f32-8398-c5a4b00499c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DrpDistrict</value>
      <webElementGuid>c3e1f3f7-be53-4564-a5aa-a93b24561dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>8dd09f20-7cb3-4def-9f30-77ac94801a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KOTA ADM. JAKARTA PUSATKOTA ADM. JAKARTA UTARAKOTA ADM. JAKARTA BARATKOTA ADM. JAKARTA SELATANKOTA ADM. JAKARTA TIMURKAB. ADM. KEP. SERIBU</value>
      <webElementGuid>917e9d08-c624-4584-815c-a2a189bed5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DrpDistrict&quot;)</value>
      <webElementGuid>44b10aff-9e8f-4fdc-aca7-1c31f4dd905c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DrpDistrict']</value>
      <webElementGuid>8ac5be12-336c-4e23-a2a6-2ae925558e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/section/div/div/div[2]/form/section/div[5]/div/div/select</value>
      <webElementGuid>27e96138-3b9f-4237-8fdb-fed4755eb490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten/Kota'])[1]/following::select[1]</value>
      <webElementGuid>e0013978-0e33-4aa4-a46c-c5ed647c4398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi'])[1]/following::select[2]</value>
      <webElementGuid>deb71aad-1385-4839-9418-140b7dabb115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[1]/preceding::select[1]</value>
      <webElementGuid>90e9b351-f538-4005-9240-ddab75468412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan/Desa'])[1]/preceding::select[2]</value>
      <webElementGuid>49e05333-d186-4c76-9169-3100999c615d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/select</value>
      <webElementGuid>a474360f-04f0-4275-bb66-2b8cb2a93a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'city' and @id = 'DrpDistrict' and @form = '[object Object]' and (text() = 'KOTA ADM. JAKARTA PUSATKOTA ADM. JAKARTA UTARAKOTA ADM. JAKARTA BARATKOTA ADM. JAKARTA SELATANKOTA ADM. JAKARTA TIMURKAB. ADM. KEP. SERIBU' or . = 'KOTA ADM. JAKARTA PUSATKOTA ADM. JAKARTA UTARAKOTA ADM. JAKARTA BARATKOTA ADM. JAKARTA SELATANKOTA ADM. JAKARTA TIMURKAB. ADM. KEP. SERIBU')]</value>
      <webElementGuid>b2af7369-3459-48b1-ae54-e8001b12373a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
