<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TxtNeighbourhoodReactivation</name>
   <tag></tag>
   <elementGuidId>fdc5a663-fc3d-49ac-bc8b-0243b1f171b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TxtNeighbourhood']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TxtNeighbourhood</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5dbabc80-ba9a-4731-b77a-4dc4aabe48de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rt</value>
      <webElementGuid>49f9c2d0-6daa-4a31-80fb-877dbafe9ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TxtNeighbourhood</value>
      <webElementGuid>a1b6f67e-17b8-4fa2-9b34-772d9e903a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>ae8f2436-d664-4e49-a18e-afb9ea35721a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input</value>
      <webElementGuid>c6a899b5-3221-4b13-8813-2a54fa1fad74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TxtNeighbourhood&quot;)</value>
      <webElementGuid>b08597a1-5a4d-4795-a58c-9dab7be25275</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TxtNeighbourhood']</value>
      <webElementGuid>8ea0fbd2-78cd-4287-9339-d89602948e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/section/div/div/div[2]/form/section/div[3]/div/div/div/input</value>
      <webElementGuid>0c0cc14a-179f-4620-9571-7ec8b3d7d0ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3d205bf8-56c2-4438-8103-5da5de625b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rt' and @id = 'TxtNeighbourhood' and @form = '[object Object]']</value>
      <webElementGuid>84757a15-19e3-498e-9ff9-b1bcf067d5ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
