<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TxtOTP2</name>
   <tag></tag>
   <elementGuidId>3774b670-b145-454e-b3ec-75cd8abfb5af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TxtOTP2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TxtOTP2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97dd2494-2827-4d53-ab7d-a6bd24b3add7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input TextAlign-center FontSize-xlarge</value>
      <webElementGuid>53e016f3-5931-4e47-85c1-d01533fe92a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>35f7e529-86d4-40cd-822d-7451482fa019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>66a2b460-c3e8-4931-8d58-4a7f53a12b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TxtOTP2</value>
      <webElementGuid>0c7fbf43-2b30-4327-a739-41756f62af43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OTPField2</value>
      <webElementGuid>d839adee-fbd9-47b8-b24b-ddd4e1c63913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a72219d4-41c8-4fe7-a8cb-29c2b0d1fade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TxtOTP2&quot;)</value>
      <webElementGuid>edccf0ee-7ee7-46fa-ad0b-6d9e1a33449d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TxtOTP2']</value>
      <webElementGuid>89a99ffe-1c7a-4bf7-ad57-8460aee1a37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div/div/form/div/div/div[2]/input</value>
      <webElementGuid>f43fe741-5081-4439-9bc7-bfdedf6a1bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>d469b2c6-c84a-4ec7-a1a2-ea0753991c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'TxtOTP2' and @name = 'OTPField2']</value>
      <webElementGuid>1125783f-5b1c-4ed6-b079-0281c2c78880</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
