<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AssignCardDetailFieldDeliveryRtElement</name>
   <tag></tag>
   <elementGuidId>2fd3e628-3967-416f-bf5b-5ad6d39fecad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TxtNeighbourhood</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TxtNeighbourhood']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca832d68-b20a-486d-9a05-0035a21663c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rt</value>
      <webElementGuid>c3549cd6-3ed5-44c8-860c-e49ca4bf2a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TxtNeighbourhood</value>
      <webElementGuid>7104b9fd-75cb-4f31-993c-ff4023823071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input</value>
      <webElementGuid>b1e7a0ea-268c-4562-9365-c3fe65eb63c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>002</value>
      <webElementGuid>df83005d-e028-4628-853a-c4cef25107b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TxtNeighbourhood&quot;)</value>
      <webElementGuid>98ab8c69-4cc7-4ea4-87bc-61bea1b77488</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TxtNeighbourhood']</value>
      <webElementGuid>2eef9326-ccef-41b3-bfc3-e4f4e83bb1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/div[3]/div[2]/div/section[2]/form/div[4]/div/div/div/input</value>
      <webElementGuid>a9a5af5d-3013-4f0d-b660-ea6ed31d2499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>5f2a1a3c-a9e5-45aa-bec5-ad2e9202dcf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rt' and @id = 'TxtNeighbourhood']</value>
      <webElementGuid>12d2e266-94ee-4f40-b7a6-8c0267b0ac5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
