<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtFieldBody</name>
   <tag></tag>
   <elementGuidId>e472af59-62d9-4e30-b765-287b222bec33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.jsoneditor-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div[2]/div/div/div/div[2]/div/div[19]/div/div/div/div[2]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8c4e99bc-36c2-4978-8ca0-b335653daef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsoneditor-text</value>
      <webElementGuid>13a51c1b-d2c1-455e-a3d7-958f2f1b71b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>54c10adc-8c05-4a6a-bd3f-1973795f6587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;jss1&quot;]/main[@class=&quot;jss12&quot;]/div[@class=&quot;MuiContainer-root jss13 MuiContainer-maxWidthLg&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-3&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12&quot;]/div[@class=&quot;MuiPaper-root jss14 jss15 MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiContainer-root jss72 MuiContainer-maxWidthLg&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 MuiGrid-align-items-xs-flex-start&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-9&quot;]/div[@class=&quot;jsoneditor-container&quot;]/div[@class=&quot;jsoneditor-field&quot;]/div[@class=&quot;jsoneditor jsoneditor-mode-text&quot;]/div[@class=&quot;jsoneditor-outer has-main-menu-bar has-status-bar&quot;]/textarea[@class=&quot;jsoneditor-text&quot;]</value>
      <webElementGuid>af4e972d-55a3-4185-8a59-b10e0c23117f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/div/div/div[2]/div/div[19]/div/div/div/div[2]/textarea</value>
      <webElementGuid>4e5334af-12e4-4783-b204-85b2c46df185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b1247f48-900f-49b9-b4cc-6847e790a64e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
