<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BtnSearch</name>
   <tag></tag>
   <elementGuidId>25683580-afcc-48f4-8d5b-81c5750e90d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BtnSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ab530ca4-93fa-4900-b5fd-c904afc70905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button Button--secondary UploadPhoto-button</value>
      <webElementGuid>ebab7452-96d5-4e3a-8d8c-82d9c24cce09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnSearch</value>
      <webElementGuid>4d66eae2-519f-4891-9194-703a3beb721c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e95ca6be-cda3-48e4-83ac-614b6231ab5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cari </value>
      <webElementGuid>ec824a4b-94f4-4d83-b916-7ddb1e65637c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnSearch&quot;)</value>
      <webElementGuid>024b8ec5-6311-4077-bc6b-d6f4102e4da0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnSearch']</value>
      <webElementGuid>b10c2537-dd4e-4146-9816-d351126a40bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/form/div/button</value>
      <webElementGuid>6d2df432-10d2-4871-9657-d84339b7bc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request ID'])[1]/following::button[1]</value>
      <webElementGuid>a1a53611-ed7d-498d-9dee-6283c7209e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Photo'])[3]/following::button[1]</value>
      <webElementGuid>3645559e-aa1c-49c7-9b23-192f8fd710f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detil Nasabah'])[1]/preceding::button[1]</value>
      <webElementGuid>39bf4942-b848-4038-a43c-a238471a6ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request ID'])[2]/preceding::button[1]</value>
      <webElementGuid>c7263522-745b-40c3-860d-d880778c9d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cari']/parent::*</value>
      <webElementGuid>7104ba82-ec89-4398-91e4-5de88031d2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>5b892300-09b6-482f-8c99-46fba6ae2529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnSearch' and @type = 'submit' and (text() = 'Cari ' or . = 'Cari ')]</value>
      <webElementGuid>cfd843bf-eeb3-4c5f-bec6-0ffb7110df7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
