<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LinkUploadPhoto</name>
   <tag></tag>
   <elementGuidId>7ba02b7a-a972-4ca2-8325-c1dc8d1893fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LinkUploadPhoto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LinkUploadPhoto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>712d4946-d787-416a-a641-d37db59858d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LinkUploadPhoto</value>
      <webElementGuid>055c0b64-302f-4c4c-b660-54ee0f937755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NavItem-link</value>
      <webElementGuid>1fdc4584-077b-4ff7-add0-a60dae7e10d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/upload-photo</value>
      <webElementGuid>5f42cbc3-e27f-47e4-af5e-2a2a9ec38ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload Photo</value>
      <webElementGuid>d07aa728-9fc9-4d31-bbc6-292014dfc5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LinkUploadPhoto&quot;)</value>
      <webElementGuid>b8933390-6dcf-4a99-8a79-f311bde0c6ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='LinkUploadPhoto']</value>
      <webElementGuid>9bbc67bc-db54-4fd8-ac18-869006cbb897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/ul/li[6]/a</value>
      <webElementGuid>9a4c1252-882d-4803-a4c2-1fc5ed40f421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Upload Photo')]</value>
      <webElementGuid>109f47f2-02c1-4fb1-911e-799fe6765645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leads Management'])[1]/following::a[1]</value>
      <webElementGuid>5a0ed6ad-855b-4f24-9a8c-fee388740fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSR Management'])[1]/following::a[2]</value>
      <webElementGuid>522e2a06-4fac-4fb3-aa8c-9b93cb55ce25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::a[1]</value>
      <webElementGuid>2ce69089-7851-4299-8ba5-35fade21954b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::a[2]</value>
      <webElementGuid>450bc9cb-15c3-4478-8a1c-b7957c01d184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload Photo']/parent::*</value>
      <webElementGuid>c107573f-03ef-4c10-8bbf-1a2f52deaf68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/upload-photo')]</value>
      <webElementGuid>75640745-712b-4093-a16d-f278126565ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>490d6aa2-8ac4-4fd9-9b31-e68663049429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'LinkUploadPhoto' and @href = '/upload-photo' and (text() = 'Upload Photo' or . = 'Upload Photo')]</value>
      <webElementGuid>ea0927dc-5840-4203-86b2-be31e0519eed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
