<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TxtFieldReqId</name>
   <tag></tag>
   <elementGuidId>d2cb69bb-37b7-4961-83ce-efc3f697d0b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TxtRequestId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TxtRequestId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b72ced1d-f0f5-4ae4-86c1-053d01678bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>requestId</value>
      <webElementGuid>da554332-92b9-453e-bdf9-df52ab3a4c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Request ID</value>
      <webElementGuid>4352ea6d-73fd-42c3-b8e9-a769d4bebb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TxtRequestId</value>
      <webElementGuid>47b17198-4e6a-46a4-8b47-a9889daf05f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input</value>
      <webElementGuid>09c93bee-c4b6-4989-9e52-f474ae979ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10005350</value>
      <webElementGuid>b71bd63b-2038-4006-bedb-ae840c7422f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TxtRequestId&quot;)</value>
      <webElementGuid>3e376a57-fc91-4267-b757-f1bb2eb5f7e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TxtRequestId']</value>
      <webElementGuid>37122987-2986-4e9f-a8e7-b95a4e71d9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/form/div/div/div/input</value>
      <webElementGuid>22004084-02a0-4e8b-9e86-8d06dda8a990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3795fdc6-b6dd-4904-a0ad-d81f9b3a8e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'requestId' and @placeholder = 'Cari Request ID' and @id = 'TxtRequestId']</value>
      <webElementGuid>96b08a64-6428-4d16-9b63-18a1a15c7f7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
