<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TabCardReprint</name>
   <tag></tag>
   <elementGuidId>7151c8c6-4f9a-49e2-aea8-8196ea651c3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='TabCardReprint']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TabCardReprint</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>04d86c29-e4e9-47cd-8ddb-8af3e40699f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e7fe7f5b-e9ba-4aa9-b2b5-ae4eb83fc2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TabCardReprint</value>
      <webElementGuid>8e83e6a4-900a-4f27-aea0-7fd13cc2e3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Tab Tab--active</value>
      <webElementGuid>6ea79190-bdfa-4b09-9221-f095ad7ce6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cetak Ulang</value>
      <webElementGuid>4d23c061-026d-4058-a225-208066659ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TabCardReprint&quot;)</value>
      <webElementGuid>b2afe531-2de4-464f-b4e7-7978c4978595</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='TabCardReprint']</value>
      <webElementGuid>62a18af1-0fec-4cad-9401-640e100ac321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/div/ul/li[2]</value>
      <webElementGuid>8c3d188c-80ea-4005-9b13-79dba5372618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print List'])[1]/following::li[1]</value>
      <webElementGuid>843fe645-8745-4ccc-876e-24e627438636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Printing'])[3]/following::li[2]</value>
      <webElementGuid>1fc3c8cc-22bf-4bd0-8e23-450627089511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resi'])[1]/preceding::li[1]</value>
      <webElementGuid>212394f9-5696-4117-8465-98163a369b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Per Halaman'])[1]/preceding::li[2]</value>
      <webElementGuid>a117e63b-9611-4f45-abea-9f39a1cb68b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cetak Ulang']/parent::*</value>
      <webElementGuid>b3f90d17-ee0d-43c5-a448-5381f6462754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/ul/li[2]</value>
      <webElementGuid>cbf2b196-a2c6-4e7d-a0d3-65d795ebada9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'TabCardReprint' and (text() = 'Cetak Ulang' or . = 'Cetak Ulang')]</value>
      <webElementGuid>ed11deff-a02b-4a29-80ff-97844547c994</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
