<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnFormSubmitSenyumku</name>
   <tag></tag>
   <elementGuidId>59538dd4-b1e3-4770-a7a7-97d84ce71606</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnFormSubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnFormSubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4bd6147d-7e1e-40a5-a2a8-ab1af9090f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button Button--secondary Button--fullWidth</value>
      <webElementGuid>b7fcac9a-8b21-46d4-afcc-94816932503f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnFormSubmit</value>
      <webElementGuid>eda40bb6-73b0-4e7b-8aa2-5963dcb9823c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7895b524-098d-409d-9d39-da6ecfa03570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kirim formulir</value>
      <webElementGuid>80ff5e08-d785-414e-8d1c-f515c5a1b2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnFormSubmit&quot;)</value>
      <webElementGuid>826c5150-cf12-439f-a75d-b47f3ad47e18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnFormSubmit']</value>
      <webElementGuid>8b82ecf9-b8a5-4fd9-82af-06d4dfc1e306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/section/div/div/div[2]/form/section/div[9]/div/button</value>
      <webElementGuid>73436b28-22e6-43d7-838e-c813adba7cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asad'])[1]/following::button[1]</value>
      <webElementGuid>508e2bcf-faf6-445c-8a96-4749e614d40c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alasan pemblokiran akun'])[1]/following::button[1]</value>
      <webElementGuid>020e502d-f247-4879-89a9-a705504b9dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senyumku adalah produk PT Bank Amar Indonesia yang terdaftar dan diawasi oleh'])[1]/preceding::button[1]</value>
      <webElementGuid>ccfc27ec-2772-477c-8b46-b8924b0fe42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Senyumku'])[1]/preceding::button[1]</value>
      <webElementGuid>e3a2974a-f9fa-4dcb-a316-e6e123a02f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kirim formulir']/parent::*</value>
      <webElementGuid>a185df01-e5b0-4741-a347-6bc87eba6ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/button</value>
      <webElementGuid>5f8fbb0f-28bf-485e-8981-f23c4e6b0e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnFormSubmit' and @type = 'button' and (text() = 'Kirim formulir' or . = 'Kirim formulir')]</value>
      <webElementGuid>1b7026b1-8f21-484a-98c0-84fb04049337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
