<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RbNoChgPhoneNo</name>
   <tag></tag>
   <elementGuidId>044253fe-5ed3-4e10-892a-5ef516ee0d46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RbChgPhoneNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RbChgPhoneNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c590b67-7f7c-4008-8fd4-4f06d5e0aca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>changephone</value>
      <webElementGuid>51b809d7-d34b-45c3-9cfe-e9c01a126d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RbChgPhoneNo</value>
      <webElementGuid>852af371-80b4-43ce-9573-7bfb4bf50915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8d82f468-c5c3-42fd-8b70-34bd3d776bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d2fe8d5f-b7bb-403a-aed6-c56eb74d5336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RbChgPhoneNo&quot;)</value>
      <webElementGuid>5b3034de-e4cf-4822-ab5a-8bff3066b998</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RbChgPhoneNo']</value>
      <webElementGuid>41b584b7-26e7-4a70-ab89-652fc5c2822a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/form/section/div[4]/div[3]/input</value>
      <webElementGuid>fb42f238-da96-412c-b55e-be74c2b19cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/input</value>
      <webElementGuid>d0e0266a-64b1-479e-be52-e5d9d711a6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'changephone' and @id = 'RbChgPhoneNo' and @type = 'radio']</value>
      <webElementGuid>7018e3ca-67fc-4f14-9691-0529d72b6c99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
