<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BtnFmVerihub</name>
   <tag></tag>
   <elementGuidId>f4143c1c-2742-49d5-a495-c5e9a1e83dce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnFacematchVerihub']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnFacematchVerihub</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a01cb9db-5ddd-494d-aaae-64f4346b6938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button Button--primary</value>
      <webElementGuid>26a4ee4f-da10-4bfc-bb9a-cc4eb093d108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnFacematchVerihub</value>
      <webElementGuid>89c59346-9f4a-417d-94a4-59644613a55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>BtnFacematchVerihub</value>
      <webElementGuid>8c42847c-d5d3-4c32-a58a-b5c9aee149b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cek </value>
      <webElementGuid>5bc8bb7e-5847-46a7-a104-7f03258d6942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnFacematchVerihub&quot;)</value>
      <webElementGuid>8d5927a3-2141-4a4b-9cd1-1404feda6528</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnFacematchVerihub']</value>
      <webElementGuid>0eea18fc-dcaf-4b9c-9ce7-876758c3f864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/div[4]/section[2]/div/div/div[2]/table/tbody/tr[3]/td[3]/button</value>
      <webElementGuid>b656afff-e471-43da-94bc-5ea1fc9f6107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[1]</value>
      <webElementGuid>89c8d817-b647-4463-ae1e-6a3e5cde4f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Face Match Verihub'])[1]/following::button[1]</value>
      <webElementGuid>e6ed397c-5d8c-4e73-8d1b-207b7e86d773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto Diri'])[2]/preceding::button[1]</value>
      <webElementGuid>eac13926-7c5e-434e-afeb-91231a99934e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data eKTP'])[1]/preceding::button[1]</value>
      <webElementGuid>cbef3c25-71a4-4eec-a8a9-92f8c499b2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/button</value>
      <webElementGuid>02f7e561-d46e-456f-95de-dfac7f35b68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnFacematchVerihub' and (text() = 'Cek ' or . = 'Cek ')]</value>
      <webElementGuid>5c0914a4-e08a-4897-9abc-e7092813e789</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
