<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChkBlankSelfie</name>
   <tag></tag>
   <elementGuidId>b0bc016b-67ca-47b5-84f6-cae72797a010</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ChkBlankSelfie</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ChkBlankSelfie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78181d39-7918-4118-8384-47cb1794c284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChkBlankSelfie</value>
      <webElementGuid>c951c7a9-a887-441a-b8a6-800ba78dca79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>blankSelfie</value>
      <webElementGuid>c2f01d9f-4472-4562-bb39-0045b7d430d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fd7c2174-780e-41bb-a674-09aaac66e7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>blankSelfie</value>
      <webElementGuid>b2596b01-d37f-4774-a31e-002f3aeb4736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ChkBlankSelfie&quot;)</value>
      <webElementGuid>8935bd7b-aedc-44ac-bf0e-61aeb2f4e380</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ChkBlankSelfie']</value>
      <webElementGuid>f4f283d6-d14b-4e5c-8707-3c65bc622d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outer-root']/div/div/div[2]/div/div/div/section[2]/div[2]/input</value>
      <webElementGuid>4df44d3e-39ff-46ea-81b2-9aa2e8567871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div[2]/input</value>
      <webElementGuid>968163b8-cb90-48d6-9c6f-3e61fe9e032d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ChkBlankSelfie' and @name = 'blankSelfie' and @type = 'checkbox']</value>
      <webElementGuid>26fd8acb-9316-4d23-8f44-8f9743aa3000</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
