<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChkEditedSelfie</name>
   <tag></tag>
   <elementGuidId>c5c5c264-81d2-4a9f-87d5-58e4ed0f56a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ChkEditedSelfie</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ChkEditedSelfie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c00f7c69-9395-4f78-84cb-c3ba7ea478ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChkEditedSelfie</value>
      <webElementGuid>797413e4-8991-4cce-ba84-026da953a5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>editedEKTP</value>
      <webElementGuid>ad7b1bb9-cf2d-4fc6-a60b-62b60a76138c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9b05b3e9-c4c7-4c7c-9bee-24321e4d6634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>editedEKTP</value>
      <webElementGuid>d4167579-2f30-4330-9e4f-c442dd330d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ChkEditedSelfie&quot;)</value>
      <webElementGuid>a95558e4-0cee-4ed6-807b-39741926f8d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ChkEditedSelfie']</value>
      <webElementGuid>21269dc1-114f-47e3-98d9-f79cba4b82ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outer-root']/div/div/div[2]/div/div/div/section[2]/div[3]/input</value>
      <webElementGuid>4b901afa-8f9a-4075-8588-05047d41df4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>5e3298fe-2877-41cd-ad35-8bb0a60c8db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ChkEditedSelfie' and @name = 'editedEKTP' and @type = 'checkbox']</value>
      <webElementGuid>cac60dbb-c8bc-433a-a3bc-734e2faddfc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
