<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChkFaceMatchScoreLow</name>
   <tag></tag>
   <elementGuidId>fbd82b89-61e5-441c-8d79-acfcc6c5abeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ChkFaceMatchScoreLow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ChkFaceMatchScoreLow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10b60f31-df7f-4264-8cff-83e151c91513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChkFaceMatchScoreLow</value>
      <webElementGuid>adcd9503-69df-4c97-bcdb-6786f015a709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>facematchScoreLow</value>
      <webElementGuid>ac1c5d6c-1a01-4ace-b6fa-6bdfbedd41ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>95d87895-7214-4d27-833a-33d2dc1c4ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>facematchScoreLow</value>
      <webElementGuid>162675b7-1694-4db8-82c7-40d9495831d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ChkFaceMatchScoreLow&quot;)</value>
      <webElementGuid>b7282563-d012-40f4-9b34-3849ab310d2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ChkFaceMatchScoreLow']</value>
      <webElementGuid>1b7532e6-67b9-41c1-bcc4-7f9eccb6342c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outer-root']/div/div/div[2]/div/div[3]/div/section[2]/div[2]/input</value>
      <webElementGuid>1762a8d2-c0e7-4ab1-96cc-5e2663061edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/section[2]/div[2]/input</value>
      <webElementGuid>f3580a24-b096-449b-a577-e2357920c554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ChkFaceMatchScoreLow' and @name = 'facematchScoreLow' and @type = 'checkbox']</value>
      <webElementGuid>2df1201e-48be-4f28-9c48-a56ced836318</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
