<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChkDataPrint7</name>
   <tag></tag>
   <elementGuidId>414a894b-581f-40df-aae1-938cfdde1a98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ChkDataPrint7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ChkDataPrint7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4809c39-af0b-4dbd-b18f-58ae38848520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChkDataPrint7</value>
      <webElementGuid>ea21156e-c58f-47c0-9ccf-eb56e7715e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>print</value>
      <webElementGuid>a420a08b-d0c3-4c1c-af8f-d1baa048c129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5a730258-7846-4ffe-af96-f1281b261806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10000962</value>
      <webElementGuid>71656489-4b61-4034-b68b-b56b11787eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ChkDataPrint7&quot;)</value>
      <webElementGuid>59b0e2e9-24c4-43b7-8682-fe2bfb88f188</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ChkDataPrint7']</value>
      <webElementGuid>913c603c-dad0-4cd0-8298-7a4bcc68977d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/div/div/div[2]/table/tbody/tr[7]/td[2]/div/input</value>
      <webElementGuid>9800cd16-32e6-496b-b36d-2d08effe5592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/div/input</value>
      <webElementGuid>df42b53b-8d81-42d3-ab7c-c1c65e6e3b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ChkDataPrint7' and @name = 'print' and @type = 'checkbox']</value>
      <webElementGuid>d7c063f7-72a8-476f-9005-df9b0f20c731</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
