<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChkDataPrint6</name>
   <tag></tag>
   <elementGuidId>5127109f-ae9d-48fb-add3-5c0b85851925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ChkDataPrint6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ChkDataPrint6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10736a14-ba48-45ed-80f0-b97005e98380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChkDataPrint6</value>
      <webElementGuid>49ee9ec7-6d30-4363-9d75-96e84c3bbddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>print</value>
      <webElementGuid>93517689-b6e2-4d6c-aa9c-b0b6ed270845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c2e54295-80a9-48ed-97f9-e2cace48666a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10000964</value>
      <webElementGuid>018e3650-0f57-48b7-8917-5fa532435cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ChkDataPrint6&quot;)</value>
      <webElementGuid>9b8aed61-6000-429c-80d8-bb0f778dcf9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ChkDataPrint6']</value>
      <webElementGuid>18acdd3d-bb5f-495d-82b2-2cd85383583f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/div/div/div[2]/table/tbody/tr[6]/td[2]/div/input</value>
      <webElementGuid>2208ff11-d42c-4e07-a7ac-339072c55199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/div/input</value>
      <webElementGuid>ffffc303-1de0-4350-9877-eb6fd715b074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ChkDataPrint6' and @name = 'print' and @type = 'checkbox']</value>
      <webElementGuid>4a6d8de0-69c9-4d89-903d-15769a9afbc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
