<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChkDataPrint4</name>
   <tag></tag>
   <elementGuidId>773824cf-c28c-457a-8f55-7a94ea9fc2ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ChkDataPrint4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ChkDataPrint4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06e2ffd2-f98f-4f0c-8fbf-73180818e03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChkDataPrint4</value>
      <webElementGuid>f622ff03-f47b-495e-bda5-a72a6643db53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>print</value>
      <webElementGuid>5c3f497d-3fef-47b3-9eb0-ee5b94d3d4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>db174d60-d4f9-491b-8368-1b29ed6e852c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10001093</value>
      <webElementGuid>0c9ebe42-a048-4d18-b30c-e903e61b1a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ChkDataPrint4&quot;)</value>
      <webElementGuid>06f5731d-0558-4b28-b102-4f723078416a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ChkDataPrint4']</value>
      <webElementGuid>8bb16aea-9904-45a1-8b81-540d2a6e8880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/div/div/div[2]/table/tbody/tr[4]/td[2]/div/input</value>
      <webElementGuid>3b1341e7-7f94-465b-ae30-2182d0cc8ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/input</value>
      <webElementGuid>ad614562-27a8-4fa3-8e8d-659ca45b8ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ChkDataPrint4' and @name = 'print' and @type = 'checkbox']</value>
      <webElementGuid>6c65690e-b93f-4527-868d-51294ef73c89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
