<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnReqIdFirstRow</name>
   <tag></tag>
   <elementGuidId>1011ef16-8241-40b7-9786-614586f744d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='BtnRequestId0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnRequestId0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00fc5d31-7ea4-4ea5-9d7d-89fc8f92fd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button Button--secondary Button--small</value>
      <webElementGuid>c85248ca-b49c-49b1-ba08-1fb14876d4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnRequestId0</value>
      <webElementGuid>9464c049-1ef7-491f-9213-6908a0fb7dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/kyc-management/video-verification/10004281</value>
      <webElementGuid>260fd1de-a614-4d1d-a0fc-688bd3a377f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10004281 </value>
      <webElementGuid>1a598b2a-4231-4e79-83b0-6b9a5297f793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnRequestId0&quot;)</value>
      <webElementGuid>4223f662-ee90-4129-b231-2292c67c9cec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='BtnRequestId0']</value>
      <webElementGuid>f31fa8e7-9c72-4b85-b684-9d1256342038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/div/div/div/div[2]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>692929fb-b7d4-414f-9d5a-f87cd1268a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'10004281')]</value>
      <webElementGuid>a2e01aeb-0a11-4bd0-92ab-e246dd094d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State Process'])[1]/following::a[1]</value>
      <webElementGuid>6da24927-8d93-454f-90be-b92bd1ea2a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Date'])[1]/following::a[1]</value>
      <webElementGuid>1d4ee24c-e2d3-42b2-8682-c10ce0b38050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrasi Baru'])[1]/preceding::a[1]</value>
      <webElementGuid>9d92417b-60d1-4a9f-ae29-1c976ea3d27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROSUL'])[1]/preceding::a[1]</value>
      <webElementGuid>d3938287-0442-4622-ae97-41af29a6323e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10004281']/parent::*</value>
      <webElementGuid>165d21c8-41a5-49aa-9ec8-91a2e605c6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/kyc-management/video-verification/10004281')]</value>
      <webElementGuid>e235fb18-3fa1-4779-be6f-9dc2479625b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>43c4493d-c9ef-40f5-b455-d4e8c80741f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'BtnRequestId0' and @href = '/kyc-management/video-verification/10004281' and (text() = '10004281 ' or . = '10004281 ')]</value>
      <webElementGuid>d5c842a0-45ad-4cd1-a5cc-a718bd583102</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
