<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AssignCardRequestIdDetail</name>
   <tag></tag>
   <elementGuidId>113033e1-d21d-4080-81a2-c0ba57e73582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='BtnReqId1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnReqId1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dc6d3aa5-0cdc-47c1-821a-b9275916a6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button Button--secondary Button--small</value>
      <webElementGuid>341d88a7-92db-4558-a23c-855413c4b7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnReqId1</value>
      <webElementGuid>1ee137af-d4ec-4acd-9747-ac6e9f806642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/card-management/assign-card/10001081</value>
      <webElementGuid>6c8a622a-167d-40bf-9351-f85665acd352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10001081 </value>
      <webElementGuid>733020dc-944c-4188-83ca-f4667ea29f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnReqId1&quot;)</value>
      <webElementGuid>11217d0e-74e7-4bbb-b6fe-23f049295936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='BtnReqId1']</value>
      <webElementGuid>428573a5-5ca1-46eb-80f4-821bd1bc1dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/section/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>43392bbd-aae0-430f-8dbe-db10bbfde6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'10001081')]</value>
      <webElementGuid>47c99d48-28d7-454f-8e19-b67ea381e28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State Process'])[1]/following::a[1]</value>
      <webElementGuid>ce35eb03-4844-4a21-974b-9a0c8faa2abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Origin'])[1]/following::a[1]</value>
      <webElementGuid>e7b3cfff-3cf3-478d-9f7d-65f74be1b3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEDDY GUTOYO JATMIKO'])[1]/preceding::a[1]</value>
      <webElementGuid>ff4ecccd-5ec6-4312-8564-a471bd5bb8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu Baru'])[2]/preceding::a[1]</value>
      <webElementGuid>e0965615-416d-4962-bddf-499663d20f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10001081']/parent::*</value>
      <webElementGuid>3fc42d8f-4641-498c-b019-16b460c8abef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/card-management/assign-card/10001081')]</value>
      <webElementGuid>4eec240b-0208-4a26-a814-7dfb63999f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>0f62d2e6-3e8a-49c7-a84f-4b0d2245db2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'BtnReqId1' and @href = '/card-management/assign-card/10001081' and (text() = '10001081 ' or . = '10001081 ')]</value>
      <webElementGuid>766b6240-6e08-40f2-b199-20f105c4cb19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
