<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AssignCardPopUpNotification</name>
   <tag></tag>
   <elementGuidId>a48656ca-2b40-47a5-894f-8b94579dffb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outer-root']/div/div/section</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.u-ta-center.u-pd-large</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>a4f06911-683b-4045-a3be-9733101f6c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-ta-center u-pd-large</value>
      <webElementGuid>5f8fde09-954c-40b5-9c11-f2cf0e92a298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KonfirmasiNasabah ini masih dalam proses. Mohon untuk dilanjutkan terlebih dahuluLanjutkan Batal </value>
      <webElementGuid>77a597c6-de9d-4c94-92a5-85e5b932c810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outer-root&quot;)/div[@class=&quot;Modal is-opened&quot;]/div[@class=&quot;Modal-dialog&quot;]/section[@class=&quot;u-ta-center u-pd-large&quot;]</value>
      <webElementGuid>d04f09d7-3ae4-4ab3-98fd-c8056e7af4af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outer-root']/div/div/section</value>
      <webElementGuid>13dae2c3-c095-4a49-a228-009a1b465ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedang diproses'])[1]/following::section[1]</value>
      <webElementGuid>545348f0-b45e-4384-bcbd-a0e7814adaf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/section</value>
      <webElementGuid>c61713e9-3123-4f9c-b0c1-e91d4dead807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'KonfirmasiNasabah ini masih dalam proses. Mohon untuk dilanjutkan terlebih dahuluLanjutkan Batal ' or . = 'KonfirmasiNasabah ini masih dalam proses. Mohon untuk dilanjutkan terlebih dahuluLanjutkan Batal ')]</value>
      <webElementGuid>49cf77d8-a684-4313-b66c-eccfcc7d8762</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
