<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BtnFirstPageAirwayBill</name>
   <tag></tag>
   <elementGuidId>9f2946f1-c0e4-438d-91d2-934ae0631458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='BtnFirstPageAirwayBill']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnFirstPageAirwayBill</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>428ee46b-12ef-4159-bc90-9c648490b541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TablePagination-page TablePagination-first</value>
      <webElementGuid>0c1fb38f-680a-4419-a3a7-591b88ff9b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnFirstPageAirwayBill</value>
      <webElementGuid>dc907df8-3d09-4c52-92ad-e6dcd732741f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnFirstPageAirwayBill&quot;)</value>
      <webElementGuid>323d57a9-0842-4e3c-b78c-822bb0d0f477</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='BtnFirstPageAirwayBill']</value>
      <webElementGuid>093344c9-e0e8-4003-ae86-915defe711a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/div/div/div[3]/div[2]/ul/li</value>
      <webElementGuid>7941be7e-2f64-4b18-91eb-90e786885765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DONE'])[10]/following::li[1]</value>
      <webElementGuid>31261709-5139-474e-b749-b2565e9bc391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permintaan Kartu Baru'])[3]/following::li[1]</value>
      <webElementGuid>4053ef3f-a501-4b2e-abfc-fd6aaa6c5d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak Resi'])[1]/preceding::li[6]</value>
      <webElementGuid>e341eb2c-06a4-43e0-b15f-bc766f89cd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li</value>
      <webElementGuid>45f2e031-48e5-4c73-91cb-fd595d646491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'BtnFirstPageAirwayBill']</value>
      <webElementGuid>adead5df-f6df-4d25-91b0-2b0b602d67f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
