<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BtnPreviousPageAirwayBill</name>
   <tag></tag>
   <elementGuidId>ac31bad2-b097-4181-ade0-24e8ac64a8b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='BtnPreviousPageAirwayBill']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnPreviousPageAirwayBill</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b1baefd9-5ce1-48cc-8aa3-20a2d252909d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnPreviousPageAirwayBill</value>
      <webElementGuid>4509c137-184c-4a93-b3b1-3b6c4e754e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TablePagination-page TablePagination-prev</value>
      <webElementGuid>0b56b687-085b-4e0d-829d-3010a497a2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnPreviousPageAirwayBill&quot;)</value>
      <webElementGuid>f21bdc83-5938-4e35-be63-c22343a925f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='BtnPreviousPageAirwayBill']</value>
      <webElementGuid>d5246fa4-1e9a-44dd-b654-e2772e62ac4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/div/div/div[3]/div[2]/ul/li[2]</value>
      <webElementGuid>15f42025-bac1-42bc-909f-b18401f74057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DONE'])[10]/following::li[2]</value>
      <webElementGuid>242f9bc8-4042-4bab-b04f-c21627a41c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permintaan Kartu Baru'])[3]/following::li[2]</value>
      <webElementGuid>7a081517-52f9-4754-a67b-bd3bf5831d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak Resi'])[1]/preceding::li[5]</value>
      <webElementGuid>5dc1d0be-b57a-456a-a227-62e726394307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]</value>
      <webElementGuid>fda45e34-b9be-40aa-8d9e-44d1c695b691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'BtnPreviousPageAirwayBill']</value>
      <webElementGuid>d79f2d89-e86f-4618-a9ee-fdd3564b20bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
