<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DrpDataInPageAirwayBill</name>
   <tag></tag>
   <elementGuidId>c23788a2-7117-4c68-9365-9d28731127e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DrpDataInPageAirwayBill']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DrpDataInPageAirwayBill</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>351f9dec-8fc9-4734-aba9-a82b64160f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DrpDataInPageAirwayBill</value>
      <webElementGuid>4c6c2001-7d73-4afc-a4b4-f27efa9528c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10501002505001000</value>
      <webElementGuid>9e21f3f9-2fec-4b65-83d3-de606ea83c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DrpDataInPageAirwayBill&quot;)</value>
      <webElementGuid>bacfd909-4eec-48c7-a574-04294384c359</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DrpDataInPageAirwayBill']</value>
      <webElementGuid>597e9c03-88ed-46f5-af15-b0f654f11321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/div/div/div/div[2]/div/div/select</value>
      <webElementGuid>aedc7510-996d-4d30-85f1-6a6159d5fda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Per Halaman'])[1]/following::select[1]</value>
      <webElementGuid>f782c22d-e1a7-496d-9657-2add8605a825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Resi'])[1]/following::select[2]</value>
      <webElementGuid>84688cc0-8828-4284-bb6a-8af33c5ee66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::select[1]</value>
      <webElementGuid>91a92f1a-773a-4402-a132-d6b101461ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Semua'])[1]/preceding::select[1]</value>
      <webElementGuid>696a7e08-3257-4a7f-837f-05d252335620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>bd5f17f0-2e6e-491e-ac6c-1a6644e169a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DrpDataInPageAirwayBill' and (text() = '10501002505001000' or . = '10501002505001000')]</value>
      <webElementGuid>422d9534-d16a-44b9-9ee8-70bc90f47057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
