<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CSRManagementBucketListDrpFilterByCardStatus</name>
   <tag></tag>
   <elementGuidId>a2e5d269-995f-42b0-92f1-afaf881175ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DrpFilterByCardStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DrpFilterByCardStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>44f4e28a-a3cc-457c-ad42-559f0a6dd270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DrpFilterByCardStatus</value>
      <webElementGuid>9087d82c-24c0-4d9e-b9c3-7b579ce74f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SemuaBelum AktivasiSudah AktivasiBlock Kartu ATMPermintaan Kartu Baru</value>
      <webElementGuid>76ad085a-e8f6-4013-9608-60f89199b7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DrpFilterByCardStatus&quot;)</value>
      <webElementGuid>567455ae-2379-4352-8276-adc4df7b5cfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DrpFilterByCardStatus']</value>
      <webElementGuid>ad353fa0-b285-4bbe-9e5a-d6afe14a2acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div[2]/div/div/select</value>
      <webElementGuid>e9927bb2-9e80-4164-90d8-fffd17491d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter Card Status'])[1]/following::select[1]</value>
      <webElementGuid>7604b344-a8b3-4967-98e3-3b2270540c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan'])[1]/following::select[1]</value>
      <webElementGuid>65ef2795-b6f4-43a1-9228-5188089b27fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter Customer Type'])[1]/preceding::select[1]</value>
      <webElementGuid>5ff4e3fc-6602-4d31-93b2-4b2090884003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::select[2]</value>
      <webElementGuid>bd80f266-6bfd-4ba4-aa2c-3a69a638d42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>340578df-4bc1-4b80-8ea1-1b87a06829fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DrpFilterByCardStatus' and (text() = 'SemuaBelum AktivasiSudah AktivasiBlock Kartu ATMPermintaan Kartu Baru' or . = 'SemuaBelum AktivasiSudah AktivasiBlock Kartu ATMPermintaan Kartu Baru')]</value>
      <webElementGuid>c6705489-5df4-465d-82d4-1f6a1ff48183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
