<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CSRManagementBucketListAlertWrongSecQuest</name>
   <tag></tag>
   <elementGuidId>b994bf8a-2340-4c00-86e0-78c4a685a1a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outer-root']/div/div/form/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.u-Color-danger.u-MarginBottom-small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2e5d1df8-974b-4f20-a07c-9b4a2da6805c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-Color-danger u-MarginBottom-small</value>
      <webElementGuid>763d3b49-b87d-482a-b29f-8f9bd555fe05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kesempatan menjawab tersisa 2</value>
      <webElementGuid>7bb7cef5-1983-4d65-91a9-1b31aa531205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outer-root&quot;)/div[@class=&quot;Modal is-opened&quot;]/div[@class=&quot;Modal-dialog SecurityQuestion&quot;]/form[@class=&quot;Form&quot;]/span[@class=&quot;u-Color-danger u-MarginBottom-small&quot;]</value>
      <webElementGuid>b8c1cf22-961f-4cd7-9371-0864bf9b523f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outer-root']/div/div/form/span</value>
      <webElementGuid>405df38c-1e50-4f68-b9e9-73b0e078618a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Ibu Kandung'])[1]/following::span[1]</value>
      <webElementGuid>0b6bcb03-bd26-4686-90ec-1674f76e77a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEWSTAGING TEST'])[3]/following::span[1]</value>
      <webElementGuid>71826bf2-04d9-4762-9c60-e1a04ce0f527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan'])[1]/preceding::span[1]</value>
      <webElementGuid>2674aeb9-0a80-4386-8e2d-4fdd65fc40ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::span[1]</value>
      <webElementGuid>3e53dd0b-5eee-4289-9218-93b1d1faab4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kesempatan menjawab tersisa']/parent::*</value>
      <webElementGuid>67e31539-0e44-4a21-b26a-bb2abbcee511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/span</value>
      <webElementGuid>18464883-c4a6-4767-b77f-ec81ca9ff6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Kesempatan menjawab tersisa 2' or . = 'Kesempatan menjawab tersisa 2')]</value>
      <webElementGuid>fd495214-1dcc-4c3f-b797-fb5eb37d73d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
