<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CSRManagementBucketListTxtBirthdaySecQuest</name>
   <tag></tag>
   <elementGuidId>197ddc1f-c3e1-4db9-bd55-f8d3ca5ffeee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DtpBirthDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DtpBirthDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e0af0e4-efdc-478e-b686-b2611ea314b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1506ed8f-cf7a-4288-a775-1f8dcad7e481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DtpBirthDate</value>
      <webElementGuid>a2f9a516-690d-489f-ab6a-24c74e98e18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthdate</value>
      <webElementGuid>7bd263c7-4864-4849-aafc-eefda67abb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>f3267955-350c-405b-9b5d-ac9963c64ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>31/12/2022</value>
      <webElementGuid>515cf64a-7127-49c6-9c85-b2a4075bbad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DtpBirthDate&quot;)</value>
      <webElementGuid>659df37a-1e5f-4514-8b33-42ab3426be40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DtpBirthDate']</value>
      <webElementGuid>818eb12a-77c8-4b6e-b5b5-ff4523c1a144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outer-root']/div/div/form/div/div/div/div/input</value>
      <webElementGuid>4e19c718-6e6d-4869-9a4c-fa132a444d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/input</value>
      <webElementGuid>968c50b1-eb42-461b-a254-3b183d3acc2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DtpBirthDate' and @name = 'birthdate']</value>
      <webElementGuid>013280ac-3664-4421-a82b-f3130e06581e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
